### ISSUE TITLE
Duplicated Files  e.g. Andrew Adane, others?

### ISSUE THREAD

**Issue by asamoal** [Data-Mavens-io/vinterns2021#16]
@dewdrew you have duplicated your files so have a look at how you can delete the wrong file before or during your next update.

Remember that it is your responsibility to keep the repo clean and relevant; so while you create a new and more correct file you should remove the old one and thus, make sure that you are running a full 'git pull' to get the latest updates on the repo.

**Comment by felaris** [comment]
Done , fetched and merged now have the updated repo , thank you
